version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
    deploy:
      resources:
        limits:
          cpus: '0.5' 
          memory: 512M  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
      - ./offers.xml:/app/offers.xml 
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: marketplace
    command: >
      sh -c "while ! nc -z postgres 5432; do
              echo 'Waiting for PostgreSQL...';
              sleep 3;
           done;
           python main.py"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  elasticsearch-mapping:
    image: curlimages/curl:latest 
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./mapping.json:/app/mapping.json
    entrypoint: >
      sh -c "while ! nc -z elasticsearch 9200; do
              echo 'Waiting for Elasticsearch...';
              sleep 3;
           done;
           echo 'Elasticsearch is available. Applying index mapping...';
           curl -X DELETE "http://elasticsearch:9200/products";
           curl -X PUT 'http://elasticsearch:9200/products/_mapping' \
               -H 'Content-Type: application/json' \
               -d @/app/mapping.json"

volumes:
  postgres_data:
  es_data: